name: build-image

on:
  push:
    branches:
      - 'deploy'
env:
  AWS_REGION: us-east-1

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{env.AWS_REGION}}

      - name: Update KubeConfig
        run: | 
              mkdir -p $HOME/.kube
              echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config
              aws eks update-kubeconfig --region us-east-1 --name eks-lab

      - name: List all pods
        uses: actions-hub/kubectl@master
        with:
          args: get pods -A

      - name: Deploy application
        uses: actions-hub/kubectl@master
        with:
          args: create -f app.yaml
