name: deploy-app

on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{env.AWS_REGION}}

      - name: Update KubeConfig
        run: echo KUBE_CONFIG=$(aws eks update-kubeconfig --region us-east-1 --name eks-lab --dry-run | base64) >> $GITHUB_ENV

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ env.KUBE_CONFIG }}
      - run: kubectl get pods -A

      - name: Render k8s manifest and deploy
        env:
          DOCKER_IMAGE: ${{needs.build-image.outputs.docker-image-ref}}
        with:
          base64-kube-config: ${{ env.KUBE_CONFIG }}
        run: |
          envsubst < app.template.yaml > deployment.yml
          kubectl apply -f deployment.yml
